name: hello-world-example
on:
  push:
    paths:
      - '.github/workflows/01-hello-world.yml'
jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      -
        name: Say Hello
        run: echo "Hello world!"
      -
        name: Do stuff
        run: |
          echo "Step 1..."
          echo "Step 2..."
          echo "Step 3..."
          echo "Step 4..."
      -
        name: Say Goodbye
        run: echo "Goodbye!"