name: event-triggers-example
on:
  push:
    branches: 
      - '02-develop'
      - '02-foo/*'
      - '02-foo/**'
      - '!02-foo/*/456'
    tags:
      - '*'
    paths:
      - '.github/workflows/02-event-triggers.yml'
  pull_request:
    branches:
      - '02-develop'
    paths:
      - '.github/workflows/02-event-triggers.yml'
  schedule:
    - cron: '*/15 * * * *'
jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Print current path
        working-directory: ./02-event-triggers
        run: pwd

      - name: Event
        run: echo "Triggered by $GITHUB_EVENT_NAME"

      - name: Say Hello
        run: echo "Hello world!"