name: actions-example
on:
  push:
    paths:
      - '03-actions/**.js'
      - '.github/workflows/03-actions.yml'
jobs:
  use-actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '15.8.0'
      -
        name: Install repo dependencies
        working-directory: ./03-actions
        run: npm install
      -
        name: Run script from repo
        working-directory: ./03-actions
        run: node helloWorld.js