name: env-vars-example
on:
  push:
    paths:
      - '.github/workflows/04-environment-variables.yml'
env:
  VENI: 'I came'
jobs:
  use-env-vars:
    runs-on: ubuntu-latest
    env:
      VIDI: 'I saw'
    steps:
      - uses: actions/checkout@v2

      - name: Print current path
        working-directory: ./04-environment-variables
        run: pwd
      
      - name: Show me the vars
        run: echo "$VENI, $VIDI, $VICI"
        env:
          VICI: 'I conquered'
      
      - name: Create env var
        run: echo "foo=bar" >> $GITHUB_ENV
      
      - name: Useful default vars
        run: |
          echo "Workflow name:  $GITHUB_WORKFLOW"
          echo "Workspace:      $GITHUB_WORKSPACE"
          echo "Event:          $GITHUB_EVENT_NAME"
          echo "SHA:            $GITHUB_SHA"
          echo "Ref:            $GITHUB_REF"

      - name: Show env variables list
        run: env