
name: parallel-jobs
on:
  push:
    paths:
      - '.github/workflows/05-parallel-jobs.yml'

jobs:
  job-a:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Doing work"
  job-b:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Print current path
        working-directory: ./05-parallel-jobs
        run: pwd

      - run: echo "More work at the same time"