name: job-matrix

on:
  push:
  
jobs:
  my-job:
    strategy:
      matrix:
        os: [ubuntu-18.04, ubuntu-22.04]
        node: [12, 14, 16]
        exclude:
        - os: ubuntu-18.04
          node: 12

    runs-on: ${{ matrix.node }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          
      - name: Print OS-release
        run: cat /etc/os-release
        
      - name: Install dependencies
        working-directory: ./07-job-matrix
        run: npm ci
        
      - name: Run tests
        working-directory: ./07-job-matrix
        run: npm test
