name: job-matrix

on:
  push:
    paths:
      - '07-job-matrix/**'
      - '.github/workflows/07-job-matrix.yml'
  
jobs:
  my-job:
    strategy:
      matrix:
        os: [ubuntu-18.04, ubuntu-22.04]
        node: [14, 16, 18]
        exclude:
        - os: ubuntu-18.04
          node: 14

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          
      - name: Print OS-release
        run: cat /etc/os-release
        
      - name: Install dependencies
        working-directory: ./07-job-matrix
        run: npm ci
        
      - name: Run tests
        working-directory: ./07-job-matrix
        run: npm test
