name:  Get secret value

on:
  push:
    paths:
      - '.github/workflows/13-get-secret-value.yml'

# Create a secret with the name `NEW_SECRET` or replace it with the name of the existing secret to see the value of secret
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Echo secret's value
        run: |
          echo "MASKED=${{ secrets.NEW_SECRET }}" >> $GITHUB_ENV

      - name: Echo unmasked secret's value
        run: |
          echo ${{ secrets.NEW_SECRET }} | sed 's/./& /g' | sed 's/ //g'
          unmasked=$(echo ${{ secrets.NEW_SECRET }} |  sed 's/./& /g' | sed 's/ //g')
          echo "UNMASKED=$unmasked" >> $GITHUB_ENV

      - name: Echo env secrets
        run: |
          echo "masked: ${{ env.MASKED }}"
          echo "unmasked: ${{ env.UNMASKED }}"